//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AevumRebuild.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorkID { get; set; }
        public int Date { get; set; }
        public string WorkTitle { get; set; }
        public string AuthorName { get; set; }
        public string AuthorSurName { get; set; }
        public string WorkDescription { get; set; }
        public string ManuscriptType { get; set; }
        public string LocationWritten { get; set; }
        public string LocationFound { get; set; }
        public string CurrentLocation { get; set; }
        public int Category { get; set; }
        public string NotesOnWork { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
